#!/usr/bin/env ruby

# frozen_string_literal: true

require "clamp"
require_relative "days/days"

Clamp do
  option "--day", "DAY", "solution for day to run", required: true do |s|
    Integer(s)
  end

  def execute
    executer_class = Object.const_get("Days::Day#{day}::Executer")
    executer = executer_class.new(input_file_path: input_file_path(day))
    puts "==========="
    puts "Day #{day}"
    puts "==========="
    puts "1) #{executer.solution_1}"
    puts "2) #{executer.solution_2}"
  # rescue NameError => e
  #   puts e
  #   signal_usage_error "Invalid Day #{day}"
  end

  def input_file_path(day)
    File.join(__dir__, "./inputs/#{day}.txt")
  end
end
