#!/usr/bin/env ruby

# frozen_string_literal: true

require "clamp"
require_relative "days/days"

Clamp do
  option "--day", "DAY", "solution for day to run", required: true do |s|
    Integer(s)
  end

  def execute
    solution_class = Object.const_get("Days::Day#{day}")
    solver = solution_class.new(input_file_path: input_file_path(day))
    puts "==========="
    puts "Day #{day}"
    puts "==========="
    puts "1) #{solver.solve_1}"
    puts "2) #{solver.solve_2}"
  rescue NameError
    signal_usage_error "Invalid Day #{day}"
  end

  def input_file_path(day)
    File.join(__dir__, "./inputs/#{day}.txt")
  end
end
